name: Java Selenium Cucumber CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verificar versión de Maven
        run: mvn -v

      - name: Ejecutar pruebas con Maven
        run: mvn clean test
        
      - name: Subir reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas
          path: target/
